added layout
Marat1922/NewsFeed pull request #1
Opened 2022-05-19 15:10 UTC by Marat1922

2022-05-19 15:55 UTC, DarthSanches requested changes
Коммит мессадж не отражает что было сделано в комиите, нужно поправить

2022-05-19 15:55 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/BaseFragment.kt
> +class BaseFragment : Fragment() {
а зачем он если нигде не используется?

2022-05-19 15:55 UTC, DarthSanches commented on app/src/main/res/layout/activity_main.xml
> +
Лишнии пустые строки

2022-05-19 15:55 UTC, DarthSanches commented on app/src/main/res/layout/activity_main.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем констрайт для такого плюшевого лайаута?

2022-05-19 15:55 UTC, DarthSanches commented on app/src/main/res/layout/fragment_all_news.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем констрайт для такого плюшевого лайаута?

2022-05-19 15:55 UTC, DarthSanches commented on app/src/main/res/layout/fragment_business_news.xml
> +<?xml version="1.0" encoding="utf-8"?>
Так если они все одинаковые почему бы не использовать одну верстку для всех фрагментов?

2022-05-24 05:27 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/MainActivity.kt
> +                0 -> tab.text = "ALL NEWS"
Захардкоженые строки их надо в strings.xml вынести

2022-05-24 05:33 UTC, DarthSanches requested changes

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/GeneralNewsFragment.kt
> +class GeneralNewsFragment: Fragment() {
так ты так и не заюзал BaseFragment

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/ScienceNewsFragment.kt
> +import com.example.newsfeed.databinding.FragmentNewsBinding
отступ

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/SportsNewsFragment.kt
> +class SportsNewsFragment: Fragment() {
снова нужен отступ

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/TechnologyNewsFragment.kt
> +class TechnologyNewsFragment: Fragment() {
и тут

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/res/layout/activity_main.xml
> +    <!--    <com.google.android.material.tabs.TabLayout-->
Коментированный код убрать

2022-05-24 05:33 UTC, DarthSanches commented on app/src/main/res/layout/activity_main.xml
> +
Лишняя пустая строка

2022-05-24 05:33 UTC, DarthSanches commented on app/build.gradle
> +
лишняя пустая строка

2022-05-24 10:36 UTC, Marat1922 commented on app/src/main/java/com/example/newsfeed/fragments/GeneralNewsFragment.kt
> +class GeneralNewsFragment: Fragment() {
Я помню. хотел следующим коммитом пушнуть

2022-05-24 10:36 UTC, Marat1922 commented on app/src/main/java/com/example/newsfeed/fragments/GeneralNewsFragment.kt
> +class GeneralNewsFragment: Fragment() {
Я помню, хотел в следующем коммите сделать.

2022-05-24 14:37 UTC, DarthSanches commented on app/src/main/java/com/example/newsfeed/fragments/GeneralNewsFragment.kt
> +class GeneralNewsFragment: Fragment() {
Тогда напиши комментарий TODO

2022-05-24 17:46 UTC, DarthSanches approved these changes

2022-05-25 15:39 UTC, merged